project.version=@project.version@
camel.version=@camel.version@
camel-spring-boot.version=@camel-spring-boot.version@
camel-quarkus.version=@camel-quarkus.version@
quarkus.version=@quarkus.version@
spring-boot.version=@spring-boot.version@
