# Spring RabbitMQ CachingConnectionFactory configuration
#
# forage.spring.rabbitmq.host=localhost
# forage.spring.rabbitmq.port=5672
# forage.spring.rabbitmq.username=guest
# forage.spring.rabbitmq.password=guest
# forage.spring.rabbitmq.virtual.host=/
# forage.spring.rabbitmq.channel.cache.size=25
# forage.spring.rabbitmq.cache.mode=CHANNEL
# forage.spring.rabbitmq.connection.cache.size=1
